In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("data.csv")
print(df.to_string)

<bound method DataFrame.to_string of    Park Code                                       Park Name       State  \
0       ACAD                            Acadia National Park          ME
1       ARCH                            Arches National Park          UT
2       BADL                          Badlands National Park          SD
3       BIBE                          Big Bend National Park          TX
4       BISC                          Biscayne National Park          FL
5       BLCA      Black Canyon of the Gunnison National Park          CO
6       BRCA                      Bryce Canyon National Park          UT
7       CANY                       Canyonlands National Park          UT
8       CARE                      Capitol Reef National Park          UT
9       CAVE                  Carlsbad Caverns National Park          NM
10      CHIS                   Channel Islands National Park          CA
11      CONG                          Congaree National Park          SC
12      CRLA                       Crater Lake National Park          OR
13      CUVA                   Cuyahoga Valley National Park          OH
14      DENA               Denali National Park and Preserve          AK
15      DEVA                      Death Valley National Park      CA, NV
16      DRTO                      Dry Tortugas National Park          FL
17      EVER                        Everglades National Park          FL
18      GAAR  Gates Of The Arctic National Park and Preserve          AK
19      GLAC                           Glacier National Park          MT
20      GLBA          Glacier Bay National Park and Preserve          AK
21      GRBA                       Great Basin National Park          NV
22      GRCA                      Grand Canyon National Park          AZ
23      GRSA     Great Sand Dunes National Park and Preserve          CO
24      GRSM             Great Smoky Mountains National Park      TN, NC
25      GRTE                       Grand Teton National Park          WY
26      GUMO               Guadalupe Mountains National Park          TX
27      HALE                         Haleakala National Park          HI
28      HAVO                  Hawaii Volcanoes National Park          HI
29      HOSP                       Hot Springs National Park          AR
30      ISRO                       Isle Royale National Park          MI
31      JOTR                       Joshua Tree National Park          CA
32      KATM               Katmai National Park and Preserve          AK
33      KEFJ                      Kenai Fjords National Park          AK
34      KOVA                      Kobuk Valley National Park          AK
35      LACL           Lake Clark National Park and Preserve          AK
36      LAVO                   Lassen Volcanic National Park          CA
37      MACA                      Mammoth Cave National Park          KY
38      MEVE                        Mesa Verde National Park          CO
39      MORA                     Mount Rainier National Park          WA
40      NOCA                    North Cascades National Park          WA
41      OLYM                           Olympic National Park          WA
42      PEFO                  Petrified Forest National Park          AZ
43      PINN                         Pinnacles National Park          CA
44      REDW                           Redwood National Park          CA
45      ROMO                    Rocky Mountain National Park          CO
46      SAGU                           Saguaro National Park          AZ
47      SEKI         Sequoia and Kings Canyon National Parks          CA
48      SHEN                        Shenandoah National Park          VA
49      THRO                Theodore Roosevelt National Park          ND
50      VOYA                         Voyageurs National Park          MN
51      WICA                         Wind Cave National Park          SD
52      WRST  Wrangell - St Elias National Park and Preserve          AK
53      YELL                       Yellowstone National Park  WY, MT, ID
54      YOSE                          Yosemite National Park          CA
55      ZION                              Zion National Park          UT

      Acres  Latitude  Longitude
0     47390     44.35     -68.21
1     76519     38.68    -109.57
2    242756     43.75    -102.50
3    801163     29.25    -103.25
4    172924     25.65     -80.08
5     32950     38.57    -107.72
6     35835     37.57    -112.18
7    337598     38.20    -109.93
8    241904     38.20    -111.17
9     46766     32.17    -104.44
10   249561     34.01    -119.42
11    26546     33.78     -80.78
12   183224     42.94    -122.10
13    32950     41.24     -81.55
14  3372402     63.33    -150.50
15  4740912     36.24    -116.82
16    64701     24.63     -82.87
17  1508538     25.32     -80.93
18  7523898     67.78    -153.30
19  1013572     48.80    -114.00
20  3224840     58.50    -137.00
21    77180     38.98    -114.30
22  1217403     36.06    -112.14
23    42984     37.73    -105.51
24   521490     35.68     -83.53
25   309995     43.73    -110.80
26    86416     31.92    -104.87
27    29094     20.72    -156.17
28   323431     19.38    -155.20
29     5550     34.51     -93.05
30   571790     48.10     -88.55
31   789745     33.79    -115.90
32  3674530     58.50    -155.00
33   669983     59.92    -149.65
34  1750717     67.55    -159.28
35  2619733     60.97    -153.42
36   106372     40.49    -121.51
37    52830     37.18     -86.10
38    52122     37.18    -108.49
39   235625     46.85    -121.75
40   504781     48.70    -121.20
41   922651     47.97    -123.50
42    93533     35.07    -109.78
43    26606     36.48    -121.16
44   112512     41.30    -124.00
45   265828     40.40    -105.58
46    91440     32.25    -110.50
47   865952     36.43    -118.68
48   199045     38.53     -78.35
49    70447     46.97    -103.45
50   218200     48.50     -92.88
51    28295     43.57    -103.48
52  8323148     61.00    -142.00
53  2219791     44.60    -110.50
54   761266     37.83    -119.50
55   146598     37.30    -113.05  >

In [5]:
data = {
    "car" : ["BMW","Ferari","Aston Martin"],
    "passings" : [3,4,5]
}

df = pd.DataFrame(data)
print(df)

            car  passings
0           BMW         3
1        Ferari         4
2  Aston Martin         5

In [6]:
data = pd.read_csv("data.csv")

df = pd.DataFrame(data)

print(df)

   Park Code                                       Park Name       State  \
0       ACAD                            Acadia National Park          ME
1       ARCH                            Arches National Park          UT
2       BADL                          Badlands National Park          SD
3       BIBE                          Big Bend National Park          TX
4       BISC                          Biscayne National Park          FL
5       BLCA      Black Canyon of the Gunnison National Park          CO
6       BRCA                      Bryce Canyon National Park          UT
7       CANY                       Canyonlands National Park          UT
8       CARE                      Capitol Reef National Park          UT
9       CAVE                  Carlsbad Caverns National Park          NM
10      CHIS                   Channel Islands National Park          CA
11      CONG                          Congaree National Park          SC
12      CRLA                       Crater Lake National Park          OR
13      CUVA                   Cuyahoga Valley National Park          OH
14      DENA               Denali National Park and Preserve          AK
15      DEVA                      Death Valley National Park      CA, NV
16      DRTO                      Dry Tortugas National Park          FL
17      EVER                        Everglades National Park          FL
18      GAAR  Gates Of The Arctic National Park and Preserve          AK
19      GLAC                           Glacier National Park          MT
20      GLBA          Glacier Bay National Park and Preserve          AK
21      GRBA                       Great Basin National Park          NV
22      GRCA                      Grand Canyon National Park          AZ
23      GRSA     Great Sand Dunes National Park and Preserve          CO
24      GRSM             Great Smoky Mountains National Park      TN, NC
25      GRTE                       Grand Teton National Park          WY
26      GUMO               Guadalupe Mountains National Park          TX
27      HALE                         Haleakala National Park          HI
28      HAVO                  Hawaii Volcanoes National Park          HI
29      HOSP                       Hot Springs National Park          AR
30      ISRO                       Isle Royale National Park          MI
31      JOTR                       Joshua Tree National Park          CA
32      KATM               Katmai National Park and Preserve          AK
33      KEFJ                      Kenai Fjords National Park          AK
34      KOVA                      Kobuk Valley National Park          AK
35      LACL           Lake Clark National Park and Preserve          AK
36      LAVO                   Lassen Volcanic National Park          CA
37      MACA                      Mammoth Cave National Park          KY
38      MEVE                        Mesa Verde National Park          CO
39      MORA                     Mount Rainier National Park          WA
40      NOCA                    North Cascades National Park          WA
41      OLYM                           Olympic National Park          WA
42      PEFO                  Petrified Forest National Park          AZ
43      PINN                         Pinnacles National Park          CA
44      REDW                           Redwood National Park          CA
45      ROMO                    Rocky Mountain National Park          CO
46      SAGU                           Saguaro National Park          AZ
47      SEKI         Sequoia and Kings Canyon National Parks          CA
48      SHEN                        Shenandoah National Park          VA
49      THRO                Theodore Roosevelt National Park          ND
50      VOYA                         Voyageurs National Park          MN
51      WICA                         Wind Cave National Park          SD
52      WRST  Wrangell - St Elias National Park and Preserve          AK
53      YELL                       Yellowstone National Park  WY, MT, ID
54      YOSE                          Yosemite National Park          CA
55      ZION                              Zion National Park          UT

      Acres  Latitude  Longitude
0     47390     44.35     -68.21
1     76519     38.68    -109.57
2    242756     43.75    -102.50
3    801163     29.25    -103.25
4    172924     25.65     -80.08
5     32950     38.57    -107.72
6     35835     37.57    -112.18
7    337598     38.20    -109.93
8    241904     38.20    -111.17
9     46766     32.17    -104.44
10   249561     34.01    -119.42
11    26546     33.78     -80.78
12   183224     42.94    -122.10
13    32950     41.24     -81.55
14  3372402     63.33    -150.50
15  4740912     36.24    -116.82
16    64701     24.63     -82.87
17  1508538     25.32     -80.93
18  7523898     67.78    -153.30
19  1013572     48.80    -114.00
20  3224840     58.50    -137.00
21    77180     38.98    -114.30
22  1217403     36.06    -112.14
23    42984     37.73    -105.51
24   521490     35.68     -83.53
25   309995     43.73    -110.80
26    86416     31.92    -104.87
27    29094     20.72    -156.17
28   323431     19.38    -155.20
29     5550     34.51     -93.05
30   571790     48.10     -88.55
31   789745     33.79    -115.90
32  3674530     58.50    -155.00
33   669983     59.92    -149.65
34  1750717     67.55    -159.28
35  2619733     60.97    -153.42
36   106372     40.49    -121.51
37    52830     37.18     -86.10
38    52122     37.18    -108.49
39   235625     46.85    -121.75
40   504781     48.70    -121.20
41   922651     47.97    -123.50
42    93533     35.07    -109.78
43    26606     36.48    -121.16
44   112512     41.30    -124.00
45   265828     40.40    -105.58
46    91440     32.25    -110.50
47   865952     36.43    -118.68
48   199045     38.53     -78.35
49    70447     46.97    -103.45
50   218200     48.50     -92.88
51    28295     43.57    -103.48
52  8323148     61.00    -142.00
53  2219791     44.60    -110.50
54   761266     37.83    -119.50
55   146598     37.30    -113.05